# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rglpm_loglkd <- function(A, tau, sig2, D) {
    .Call(`_RiemannLVM_rglpm_loglkd`, A, tau, sig2, D)
}

aux_equalstr <- function(string1, string2) {
    .Call(`_RiemannLVM_aux_equalstr`, string1, string2)
}

spherical_log <- function(x, y) {
    .Call(`_RiemannLVM_spherical_log`, x, y)
}

spherical_exp <- function(x, u, t) {
    .Call(`_RiemannLVM_spherical_exp`, x, u, t)
}

hyperbolic_log <- function(x, y) {
    .Call(`_RiemannLVM_hyperbolic_log`, x, y)
}

hyperbolic_exp <- function(x, u, t) {
    .Call(`_RiemannLVM_hyperbolic_exp`, x, u, t)
}

aux_pdist <- function(X, geometry) {
    .Call(`_RiemannLVM_aux_pdist`, X, geometry)
}

aux_pdist2 <- function(X, Y, geometry) {
    .Call(`_RiemannLVM_aux_pdist2`, X, Y, geometry)
}

aux_distVec2Mat <- function(x, Y, geometry) {
    .Call(`_RiemannLVM_aux_distVec2Mat`, x, Y, geometry)
}

aux_initembed <- function(n, p, geometry, sd) {
    .Call(`_RiemannLVM_aux_initembed`, n, p, geometry, sd)
}

src_germ <- function(D, p, geometry, iter_outer, iter_inner, tol_outer, tol_inner, exact_search, learning_rate, weight_order) {
    .Call(`_RiemannLVM_src_germ`, D, p, geometry, iter_outer, iter_inner, tol_outer, tol_inner, exact_search, learning_rate, weight_order)
}

